### ISSUE TITLE
A little confusion about readme

### ISSUE THREAD

**Issue by haorenfsa** [Azure/metaetcd#1]
Hi, I got the same idea about sharding etcd, and found this project when searching. I'm quite interested.

But I'm a bit confused about the architecture description, it says:
`The proxy watches the entire keyspace of every member cluster, buffers n messages, and replays them to clients.`

So is there only one proxy watching all the member? How to prevent the proxy becoming new bottleneck?

And, by the way, what's the strategy about paritioning? Where can I found it in the code?

**Comment by jveski** [comment]
Hi @haorenfsa -

The proxy will eventually become a bottleneck, but can still handle much more throughput than a single etcd instance. The only way around this is for clients to open watches against each member cluster, which isn't feasible for components like kube-apiserver.

Key hashing happens here: https://github.com/Azure/metaetcd/blob/main/internal/membership/pool.go#L79

Per my more recent benchmarks, this strategy can scale to around 4 member clusters before the coordinator/clock cluster becomes a bottleneck. The decision to use a logical clock here was for simplicity but to be honest I did expect it to achieve at least a bit more throughput. I'm hoping to find time soon to benchmark with a wallclock mechanism (like Spanner's).
